# Don't use the Travis Container-Based Infrastructure
sudo: true

language: java

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: oraclejdk8
    env: DISPLAY=:99.0

cache:
  directories:
  - $HOME/.m2

script:
- sh travis/build.sh

# Actions to perform after the build.
after_success:
- sh travis/tag_current_release.sh

before_deploy:
# Delete the current release version
- curl -X DELETE -uocciware:$BINTRAY_API_KEY https://api.bintray.com/packages/occiware/Multi-Cloud-Studio/update-site/versions/current-release

deploy:
  - provider: releases
    api_key:
    - secure: "iTFMImbfERKwxcGifBoTM9lgHxfM5PnOBDBcOU8V5aGOD9KwAl4DwO+o2ZqWazH2W1WAemgtB6w64uYUkcdS4lWfYMgoUIwFGjV/oq9aQXBLjmeH1WuakNkHl0i/Jq7YmCy2cyoENBbWnqNi+ToQjCD9OY2Ox678opLNtRicQjeSIOcVoZu9PL/TZMrJNNVyPujVFcdCIQF3HKWvS8HAcU/d0HRIv2IFgGUa53LGdPfIg7iBMd+DecyHBADFDdLZ8cGKEGYi6qVmbUrWPjvhTc3s4TZWqHDFbLOyOpwhYl86SJeCpVlEnkV5IhuAcQAuSJxPo//HcO04nobAFspDLgWIjmglLp91q5K8DY/8+0imjYD9ciXwSNo+1Z23i++zXChr5BEww+QKB54lH/ck7+y3rBFUCZRUmMy5YLIaiaOhmvFIn99Bqw+BEj3O6cnH1GNbG2Fl/2Fp35zvU/9NPXmI+Gb9aJForLQWROhpmef1sIViGXmipwzlVoMWzujnJJ6fu6OMaBmfKTEa1Lws5PIcTrrEknUGPl6JNYeFluaGLOUGSvCmXb8jG8rjzFZlBA0pI8ubz4l5GlGw04/P8GdU4jRRxID1QcNAwh0JjxpuvEwrZEDmAtnQPN1axIZ1xA+rw3yd595GsmcYhLH++MqJQT3hSLShuzWmopHaLkA="
    file:
      - "repositories/org.eclipse.cmf.occi.multicloud.product/target/products/org.eclipse.cmf.occi.multicloud.product-linux.gtk.x86_64.zip"
      - "repositories/org.eclipse.cmf.occi.multicloud.product/target/products/org.eclipse.cmf.occi.multicloud.product-macosx.cocoa.x86_64.zip"
      - "repositories/org.eclipse.cmf.occi.multicloud.product/target/products/org.eclipse.cmf.occi.multicloud.product-win32.win32.x86_64.zip"
    skip_cleanup: true
    overwrite: true
    on:
      branch : master
      repo: occiware/Multi-Cloud-Studio
  - provider: bintray
    file: "travis/bintray.json"
    user: "occiware"
    key:
    - secure: "0y1nU+cBPYMDHyDj+df8DdRVyZv8LzIkOitDMofEujyZ8Fr4o39E0VBXIBUV5yjMeSkI9iyvAq2FeqOmX11GRVbRlq9w64pTCD3rHtcLXHD+GcaxqfDBdPr1xopgNX7rjqfrWfHDTxgVzHNvhYBUys36ubWgFbGCBKi1i0Ra7BcAIIoLF4zcH3nwzIQrLh5cSdF9jSTPZHexzxvNvXg/hNhk2KU/DmlOalCGlb7sT2jWrUzyzQaAW0IMaHqSa9p37CKUbICOd7GI2vKCkz44LZVBkVhQC5lhlQ00t/cv2NydNEkr1YDJww9fHWW80zDvo6enVH/0LsiM/idXJA7nD97hc0MaUboW4aXzrIahRmwdBn5SspRPWwYIQSBY7RQXtx3l2FxHfGt788PTuXNzof8Gat98vR0XIq9C/hwOEXdV1FpqA+qLFRe2vkua35oF7IoOLZJV76N02cUW1QKTIOsZeOIDvZf8QXG01Luq67mZBkuW+3MSm7hSTlnBeO3+9TalNuqbwfXYHFlK8Fl19kSVjmpyEIFgp5ZqcGgBqi/U2QotpiDFtxp5gwlf22RPxLacd6Bq7s7hw4cuwxlQowDPvPjG3lUzFXKHHLpPIzlmD1u/wCKiX1HgYYz1Jk+8P3Xbif/V3Qd0QS1nqM8H2NQ8T+OUjcbXa/9c6GGwv28="
    # passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
    # dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration"
    
after_deploy:
- sh travis/deploy-maven-artifacts.sh

env:
  global:
  - secure: "zP8xzt2R7mNIaq5vjBx86KKW6O9zodADGgoimnEhF8MkHRuGwm73TiwLe877xqXAme2ODBIbVclw6L8AHwrqKC9z7Qvgsm5SJUhDVzTmp5vrSq2E39NxTrSm+tsoP+Zp9zcLPMSVx5YhsKKdXj0D2XgRN0C+lges8kz6xIo/ZeNG6Wbf3YhRXom8OHHCyTiFPnpJIuJy2vTS3mQuaqzBdp0Qol9HxfrW3SQKcadWpvnuirCCMeRtQoVjt12v3Zqkvtrpmi4wIlrS8PGooXX2ZLSiEnmhZmkyRcFkHbVmN8uaYRQarKSKYU39MgOXwG3x8ntUNsrgWaQHOxP6JQmS548hpWM6DbzpZRpf6Rp/JfWVrR7VogNYb17Aq+Nm1eo3x9lWk99fX4aRNELZYqu0hcBl7T8/aMUW7v7Z9M99z7iPEvha+aKyK9/YTV+/HjtRxrKWx2HZiMqGV+34tMqBer2j8LEMl/7o5wjaBtbYyUzz/+lrNHpKd156D7SaxMeiQCiz9Q41r5Y3KdxNZYY0lcvYhYHg2EURFh2ctViM4bgOInrSfePSGomSausQ9rUT9G8llBrarauUpBo1uY3+NH9omx41aQAyRqH9UgKUNortZcgmZ9kkRU+fBylpFm5QMyHB9R/IggUMBjojQvSm+pnFARVWS5wRsahqOCtq3WU="
  - secure: "R7bwIFP57UXHlWNDZFybUzbp4D7SgpOh1osQd8AQJb1oXSle/cYOGg8wzDOnotSbEoXEk6WiWf0ipI2QzALEgmjCf6T1m8z2ir6+B8NbA4p4BStzvIHJLogIngsOqha7uuhc7tfHo2/wVlR6EZDeeKdRw4ddEyFzWulqD5B3dzVrvI+hck86etPizxHcY5qd1endS7JDjMYtBHNDtkwTXEzzpoxypnL2+pAciGSij5XSql4IeNHAgHG3iHUzuuq+UTqKN0nBjmqFU7rTSYm2Yp3cA3JUkIcUhYu4N+cRYwsBxEWsp8treRKeX6sW2W+1DvEQ3fhOFnhChOrBg0L6Gq8UW9/Y+MpP0JqIgyOPxYKJ2Yf0uzLUY8wy06G/dkbB4Lol2ZY76ZpSyyp76HnI+SWZ/rKQuPpI/ThU3CoCRG68dIc0MOGaonmsed3EmQox73HU4xi5E5HlxRmJVM+TR1sowEwUE2lsClsJJZe1RgaXbM32mvwsZPGuEShKKndBWBdvzSZIXsg7MOX5p6rZqaMwcVydUmjF5LOs7KS0XE+NnFT2IfNZFGfjsfDKV4xGEUmJQOFHI/MhPlP5Q2gpX0fXJFQtMZhRVcYQjNUIv9xnzv6l5V2oUlIZPg6lJp5D7rWQYTUQIRMfnHg3N+G2KCM275hLZpyBByHbXoEzF/k="
  - secure: "M9F3c0nj+u2bIOUDNeKOXcgEAs8YMSNWWP00vPbH3hM6WMJauidKGn0ut5LcNVzHdZD5aFh1Q/PZDcomp8rCnZXdD2N7QfKksfbHOnsnkcxEzKjymb8KwVfJLjcl16JPDTLDzs0oZoq7L1eDIceitv/WdHrvf2/hMGPL+1JvbsoL+WlNrWVbRSUuRFHIUZaxbzuN9UPDKQgc7czTOfRZoqAc0m1CBzDZxE5EvJ6x8zSez3+EyBfGHdtO7Ua1nbvyelm+E6Hkzl7vok8aGCtRjPf2gTc5T9aq2gCBSa/ElNnBJK1TJScy/lVFQSrG1+OruTiNSIrRxKJ5JXpN+n/a9olh9U2UJc7AYsXmEIxo80PVs8f4Kdmp2s5QvcKfzlsvPB7CMIUPBKYRJtVhsD1DDEk/p3AmLDgYeXazEg94fAfvq/YgbtAkt5Y7+5HtkCY3X6txa3LHrcWiMM/c+dDy638ch2nlMjM6cbuSZLgRuEvk7sGSPXXCl9Eu38lFKKhr8NfIELsHBw2Y6RWUD5Lt7pWiSMd4UkzIBB0dMFo46X6Rfr/hdk+odBkxPgqNmz+sEIAxSkyoxmyqkuvCU1P6Xn0ScfmOjoFJEes+CU2gMNcFVd04cpF8Rnpxgo9jOcz6qFgqAt+2Ld5mC+hK/sLKMzxeD0OMbmltu3at7xTnnhw="
  - secure: "fLbNKZVacz8uoC5hXEjr/C8oO8Tg6zuRXIZJzEnKNSyCTyhsRJgZzLckF1smaPDqBDtXy/EI2TT/0PCvGlVDTXk1CbIBTYgnxH7Cgdgje6n45VQXeOJPV0uC+qXgc16XTrbfSO+EowF9FWi39ML89yxGW4yXEK7Q/YXV+jveTT3tfWzdM9ehMlhrSa3wEIem8cVBl4mDzHfefk87mHx815TiW2viVWqymN5wjCAmSvJeicTEJ5hgl4rjZ6fvRdx6KUEbhGKm+STABbVsDD8eSAA2o8Tw9uPNwecAg7cxLtI8WFcHGph1oMdNAQDjYy/6j/qM6ybKArbR2HQaDxR1y+kvnRhGfzxmDN0pbu1+PABHdfccEOq7y82CVOXCsaL8268u1p6FQ4UgdU4oE6IZfdySCDvzQ+TFZUVHW/j/jiPMHeCW92yTdo56Sa+n3dx9HPMKBDqg1d5nY2Li6g8HlAQrWiiU573UGU5mW6CHtBWKXeSbDy2yfcVuPzGFTJvgkNXrp0uFaBgDJe5tKrbX5ivomiUOy/5jUug26jI4OlWAl0zlVwQl7PHEcAGz+HjVqEkCtVqfteXsc6YbRNxznOWgUb2H/JVoXio1aX5RuwrAAhMRuwfCURYIZ8qlv4cnVRgXK148H/78D4fVt8D1AKTFHeqBKa8gCDYh34Iom/U="
