sudo: true

language: java

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: oraclejdk8
    env: DISPLAY=:99.0

# install: true
# before_install:
# - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc

cache:
  directories:
  - $HOME/.m2

script:
- sh travis/build.sh

# Actions to perform after the build.
after_success:
- sh travis/tag_current_release.sh

deploy:
    provider: releases
    api_key:
        secure: "pS0u6Wp92lFfo2K4BKCnQZIW5HzqNORSga6Xkp4aboL0sklLmhUepsOazGoGzhgoE+ZEnWwz8wlZqHTpUIsmyJkfd88mlz9Zdcz/UtBYD1/8BHI/0bGpgAjQDXofLMhDjDaxY6uu2E0/x3nIGExMp6kqj4aKAEg+ANlX64cnPmTPHhmEEBDI36aZ+f9MoYxnLN28vMrPvJHdXrMT9qEzbdMMXE/3pn6MtUh0JgduCLdwcHt0ZTRCbG//nN0I2I1qnGRj41z/016DFLyBxXPaw2dzfcMOsYDxkR8XIO/YdoEOdBjfm7h1jgcKI/2HEbORqaJ9q3VLiwrqAu/64R78GeKHgNwC9ZXBgBbhpA0h3RSfeAlfTl+7kO2wSqwF1ZhLEEe0CFNwKQJNhYqd+oj2aMf+Ua1dkCpLJFDiPTyDXM9xD2dcb44MntH1DZIwd+nD8G44ZuUj0ZmRXnUBmFgkd/griS2id233c4YYI/mz7RtTvlPdQZ8PaUsFNseQ9LcqljXnYhQixrjCpNaRHGIt2Gj4s2rEm16dTIPVQ7lCIYYZDW5/u2uhxgA1NOwxwYaJcAbPGqYG6tj1r1deJ7rxPFcaraECG6fgz+/QYmG6LiLyEyQxmTsuNgVpnv94Qu+lKUe/z3Z76y7Ho2gA/FiHaPQ/qWUR+1Rjgl3Ylg0HiPk="
    file:
        - "repositories/org.eclipse.cmf.occi.multicloud.product/target/products/org.eclipse.cmf.occi.multicloud.product-linux.gtk.x86_64.zip"
        - "repositories/org.eclipse.cmf.occi.product/target/products/org.eclipse.cmf.occi.multicloud.product-macosx.cocoa.x86_64.zip"
        - "repositories/org.eclipse.cmf.occi.product/target/products/org.eclipse.cmf.occi.multicloud.product-win32.win32.x86_64.zip"
    skip_cleanup: true
    overwrite: true
    on:
        branch : master
        repo: occiware/Multi-Cloud-Studio

after_deploy:
    - sh travis/deploy-maven-artifacts.sh

env:
  global:
  - secure: "AyGE3Mvl4DGXscKdeJbhl+I4ywtW4toEwdBl9fJtIgyaW+FcDoQKhSwWmtNwwKVO+PcB3XuFroURcv/Slomd1FFm++0IP4KRKba5IfN1jZGDL42ApAtV+dBWN6ubypO9Z4An0htlTnmCO1QKJb/Uf8o0H7GRt6mBJrBXHq2k3OK0LYfWg64R9s7ppDiT6rZwbsSLA/JOJjSD14goIyrMAIiXfqy1fOEff15B1L/g0QZNujJOOKFs9hBcI190DZqwmbbZdzKSlPQF8rq07mgonV+LFalprlrteiNzAow3efr6qTvkCi2oHNxu9Il7iO5jH/1Wbqz6X3GDzYxaFjLhCoMJrczE1XjGabvMMpLQql7rCwUwL8bSOwwtEKlgpnqP87RZ4X+Fqpg6c0/BYzXkFn2uKczh8DXh7tStkc2rt0M+wTMUKo4fWvRc00BRnr7SFevk6zeIbR85+EvJ6DBIjiEQ3/6OP8rCwSbzwk0SsxbcLT0ZzxD8kqtuBNnIeLBvnye7sUD/kySnNfSj34RkUo8HFEA8G3DOfqKE9WuAeZU9g9309CTcuJWcnqzJdv42/iNHaJo5TDWsULuWsNpRKlFuqIpn0PbECuCpH+U3TUfYg70c7bvms8b3bnC2a1Wbg6PSz5Fr+o5N3y4VvJVlxaCHNwKGeE0debRfK/5iWJ0="
  - secure: "V2y0S5RzMzNEINrZcYXYC2b1zJb9ONufhx3jd2uGFZDFie617HOW1x22ggXkg+VuVmniwes9/5A0HvXZz6ePHEFQfkUOwdOYlyIaIiLZdSDAPjznWuO0aKYAJsr7481y5BC8I5yanqREm1+3F1Hp0TI6RzNzrEwIdfdbByy0Leb+OG6ZJj5JlBYrolmIMn/hTgJ5pAeIVVwfW1Av8rm1PuIFdDFA7dL4oBSB5vQYfvHC/NQN+NmLAw1Z+DXFnKuB8R1nenr5HJ6gls/Gsqg9mV4A+USlqpPlSSxFb/8lbZUX00XUe9vTYUkpkmii939m4cBs4iFiLmnV3XN+qfcRc1chkUNcqwxNuBRQwfcOypD3ShaWXDv6NDFrlstlEHD1mZ9iZ64x33zpYuVWGzdry/qKqdWPG4Xk24c3vJ3hEXDAqwKoRNRrjtlNHXXDF1XVzWee/kbqpcs03Y/4yUOk9tr4XjlfPtuM/OxK4saEIkhMH4RL0BWUSehkLL+B6dfMXI+vOArS0NRLoPLU5fCE32N8eIuaY1yeZDmHvN5md1Z5uTAw2l8thNP/YRd+/twM3/RRHPtz5tX1hLHrNuGmYql4Bs2xCwoFUetCYZX70HHLfSdh1fTvmhnwZCxG0I7nDnVvx+rjdsLXo4dAeaR6TOj/G6uPbIolJQdW8GB/Fq0="
  - secure: "Ih21rdC59sBcW7QhcBVsXDndJBS0DReI+LNRY1ghirSR+AFx4SeF5xo9gUJhyFo21+rk+liGpxSHL5kLtoCXD8Vhrp0ZJesHzjIKFuPklCr/yH1zjVUKs0UeqbPf4wqCBR1acS67cKCy38mO0j1dlZ65hBv6VjtAkp/ENsifcZYCh5QlO+g38HcL4qHxCERFDAN40WSsM0qz8qA2kgELxjh5pFRu16/ltTPbcI2qq6ZRY2Begk8snk6ZLuGukhZ+SEnH1sd3At3cPi/ZrYfS+x7Tk0jpQKQSicntLUAr6dVErT1SS0IZMij4aUnsCoYhlTsD46HG8VNAVKgoVb3+52dysC3ewL4qvhdQIBHdWb0ULaKurSflvvUzKSip/zvo6BJq+nJ2N/+ihgMRWTHIE9u0thwzh9U07xvTTzyynz4C7PMJY/4pGsrYegiJkY6Ia11jJIPBAgz3nUI3jQAYJFISPvkjZvdAepkYAHIBPw9CP9NvY12CTelU2OdlFNaLYQjJoU8IKaAm362uuFhf8pkt977xIyDjL8XHq9uc6fKFnjiXvgFCl3eq93NMckTyXLFFvnKJ+IO+LOoWfUrGvHwJ5Xuqtq/DisL1k72/rHACwAEShGeU72JfYEurKC1gl9SxOHOn7AVVkFoof0mIBZodvvTMHpFaZVLB9aTbmQI="
  - secure: "yxwv1ZHyTdFx7nBl7ZW8wk8eGUR+dY21XfT2s4ltkKB+fj+dDLNo2pjDncVzX+ckK3a0TAMvfFUXKJ+UZHcXV3+rC6rTndJ4aOVFf9jlC+5sOfZ6w9VXgvX+H0tyk9/oAMgWVmdPCgoMAKi2POZrGKiQEMRgVY2u2oHqpiyp6lf3prBtAiXqjPx5zcxfBc1xCfzAidsFDQJJn2D+0eokLp2IDkMsz3oFdbDXfKMHXmGCwr+1y1836VKqGnUlw0KvUs/pElTy/Agrr+5wcwoGYsU13kTA2L04xM3lh4t/XVA0tgnYKJTs4s2aL8G96fucmC8WnRZOkXBjvTf5f7wWrjhj9h6rLeGNR3a3++c9OjC7VvtE81zoIt/mN3JaPW4cPlL1HR50j4GJbbB+bLbHVVzaCwXm6mV96Ma59VU7wpmUAamVBGSa6601UjSUluFU7z+6ao4nfntWrM/ncq1//Bxf58i0MBxRbkgCgxex3x19r+qghlyV7kOILyTIwNHkjkLh6vXhjxThwW2XJsOIoqw1TWXnzdPiGHt5K8BeVb6RqCROJgqNVCFXf5vRDviYP0zpe+gwgIgJy7tGXVfvlKV4WDzh4BqDRsU4qUrmkxuk8wTI+u/cywABI0qumQ71gt76M6933uiYSFXvjJCkJmYwDzu7lUdLJ88mMRiCYRY="
