/**
 * Copyright (c) 2015-2017 Obeo, Inria
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 	
 * Contributors:
 * - William Piers <william.piers@obeo.fr>
 * - Philippe Merle <philippe.merle@inria.fr>
 * - Faiez Zalila <faiez.zalila@inria.fr>
 */
package org.eclipse.cmf.occi.multicloud.aws.ec2.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.cmf.occi.multicloud.aws.ec2.util.Ec2AdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Ec2ItemProviderAdapterFactory extends Ec2AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Ec2ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Instanceec2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Instanceec2ItemProvider instanceec2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Instanceec2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstanceec2Adapter() {
		if (instanceec2ItemProvider == null) {
			instanceec2ItemProvider = new Instanceec2ItemProvider(this);
		}

		return instanceec2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Awsaccount} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AwsaccountItemProvider awsaccountItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Awsaccount}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAwsaccountAdapter() {
		if (awsaccountItemProvider == null) {
			awsaccountItemProvider = new AwsaccountItemProvider(this);
		}

		return awsaccountItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Awscredential} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AwscredentialItemProvider awscredentialItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Awscredential}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAwscredentialAdapter() {
		if (awscredentialItemProvider == null) {
			awscredentialItemProvider = new AwscredentialItemProvider(this);
		}

		return awscredentialItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_nano} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_nanoItemProvider t2_nanoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_nano}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_nanoAdapter() {
		if (t2_nanoItemProvider == null) {
			t2_nanoItemProvider = new T2_nanoItemProvider(this);
		}

		return t2_nanoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_micro} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_microItemProvider t2_microItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_micro}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_microAdapter() {
		if (t2_microItemProvider == null) {
			t2_microItemProvider = new T2_microItemProvider(this);
		}

		return t2_microItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_small} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_smallItemProvider t2_smallItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_small}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_smallAdapter() {
		if (t2_smallItemProvider == null) {
			t2_smallItemProvider = new T2_smallItemProvider(this);
		}

		return t2_smallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_medium} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_mediumItemProvider t2_mediumItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_medium}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_mediumAdapter() {
		if (t2_mediumItemProvider == null) {
			t2_mediumItemProvider = new T2_mediumItemProvider(this);
		}

		return t2_mediumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_largeItemProvider t2_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_largeAdapter() {
		if (t2_largeItemProvider == null) {
			t2_largeItemProvider = new T2_largeItemProvider(this);
		}

		return t2_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_xlargeItemProvider t2_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_xlargeAdapter() {
		if (t2_xlargeItemProvider == null) {
			t2_xlargeItemProvider = new T2_xlargeItemProvider(this);
		}

		return t2_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T2_2xlargeItemProvider t2_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T2_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT2_2xlargeAdapter() {
		if (t2_2xlargeItemProvider == null) {
			t2_2xlargeItemProvider = new T2_2xlargeItemProvider(this);
		}

		return t2_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M5_largeItemProvider m5_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM5_largeAdapter() {
		if (m5_largeItemProvider == null) {
			m5_largeItemProvider = new M5_largeItemProvider(this);
		}

		return m5_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M5_xlargeItemProvider m5_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM5_xlargeAdapter() {
		if (m5_xlargeItemProvider == null) {
			m5_xlargeItemProvider = new M5_xlargeItemProvider(this);
		}

		return m5_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M5_2xlargeItemProvider m5_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM5_2xlargeAdapter() {
		if (m5_2xlargeItemProvider == null) {
			m5_2xlargeItemProvider = new M5_2xlargeItemProvider(this);
		}

		return m5_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M5_4xlargeItemProvider m5_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM5_4xlargeAdapter() {
		if (m5_4xlargeItemProvider == null) {
			m5_4xlargeItemProvider = new M5_4xlargeItemProvider(this);
		}

		return m5_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_12xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M5_12xlargeItemProvider m5_12xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_12xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM5_12xlargeAdapter() {
		if (m5_12xlargeItemProvider == null) {
			m5_12xlargeItemProvider = new M5_12xlargeItemProvider(this);
		}

		return m5_12xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_24xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M5_24xlargeItemProvider m5_24xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M5_24xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM5_24xlargeAdapter() {
		if (m5_24xlargeItemProvider == null) {
			m5_24xlargeItemProvider = new M5_24xlargeItemProvider(this);
		}

		return m5_24xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M4_largeItemProvider m4_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM4_largeAdapter() {
		if (m4_largeItemProvider == null) {
			m4_largeItemProvider = new M4_largeItemProvider(this);
		}

		return m4_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M4_xlargeItemProvider m4_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM4_xlargeAdapter() {
		if (m4_xlargeItemProvider == null) {
			m4_xlargeItemProvider = new M4_xlargeItemProvider(this);
		}

		return m4_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M4_2xlargeItemProvider m4_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM4_2xlargeAdapter() {
		if (m4_2xlargeItemProvider == null) {
			m4_2xlargeItemProvider = new M4_2xlargeItemProvider(this);
		}

		return m4_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_10xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M4_10xlargeItemProvider m4_10xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_10xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM4_10xlargeAdapter() {
		if (m4_10xlargeItemProvider == null) {
			m4_10xlargeItemProvider = new M4_10xlargeItemProvider(this);
		}

		return m4_10xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M4_16xlargeItemProvider m4_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M4_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM4_16xlargeAdapter() {
		if (m4_16xlargeItemProvider == null) {
			m4_16xlargeItemProvider = new M4_16xlargeItemProvider(this);
		}

		return m4_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_medium} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M3_mediumItemProvider m3_mediumItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_medium}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM3_mediumAdapter() {
		if (m3_mediumItemProvider == null) {
			m3_mediumItemProvider = new M3_mediumItemProvider(this);
		}

		return m3_mediumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M3_largeItemProvider m3_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM3_largeAdapter() {
		if (m3_largeItemProvider == null) {
			m3_largeItemProvider = new M3_largeItemProvider(this);
		}

		return m3_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M3_xlargeItemProvider m3_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM3_xlargeAdapter() {
		if (m3_xlargeItemProvider == null) {
			m3_xlargeItemProvider = new M3_xlargeItemProvider(this);
		}

		return m3_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M3_2xlargeItemProvider m3_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M3_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM3_2xlargeAdapter() {
		if (m3_2xlargeItemProvider == null) {
			m3_2xlargeItemProvider = new M3_2xlargeItemProvider(this);
		}

		return m3_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C5_largeItemProvider c5_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC5_largeAdapter() {
		if (c5_largeItemProvider == null) {
			c5_largeItemProvider = new C5_largeItemProvider(this);
		}

		return c5_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C5_xlargeItemProvider c5_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC5_xlargeAdapter() {
		if (c5_xlargeItemProvider == null) {
			c5_xlargeItemProvider = new C5_xlargeItemProvider(this);
		}

		return c5_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C5_2xlargeItemProvider c5_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC5_2xlargeAdapter() {
		if (c5_2xlargeItemProvider == null) {
			c5_2xlargeItemProvider = new C5_2xlargeItemProvider(this);
		}

		return c5_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C5_4xlargeItemProvider c5_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC5_4xlargeAdapter() {
		if (c5_4xlargeItemProvider == null) {
			c5_4xlargeItemProvider = new C5_4xlargeItemProvider(this);
		}

		return c5_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_9xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C5_9xlargeItemProvider c5_9xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_9xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC5_9xlargeAdapter() {
		if (c5_9xlargeItemProvider == null) {
			c5_9xlargeItemProvider = new C5_9xlargeItemProvider(this);
		}

		return c5_9xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_18xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C5_18xlargeItemProvider c5_18xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C5_18xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC5_18xlargeAdapter() {
		if (c5_18xlargeItemProvider == null) {
			c5_18xlargeItemProvider = new C5_18xlargeItemProvider(this);
		}

		return c5_18xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C4_largeItemProvider c4_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC4_largeAdapter() {
		if (c4_largeItemProvider == null) {
			c4_largeItemProvider = new C4_largeItemProvider(this);
		}

		return c4_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C4_xlargeItemProvider c4_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC4_xlargeAdapter() {
		if (c4_xlargeItemProvider == null) {
			c4_xlargeItemProvider = new C4_xlargeItemProvider(this);
		}

		return c4_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C4_2xlargeItemProvider c4_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC4_2xlargeAdapter() {
		if (c4_2xlargeItemProvider == null) {
			c4_2xlargeItemProvider = new C4_2xlargeItemProvider(this);
		}

		return c4_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C4_4xlargeItemProvider c4_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC4_4xlargeAdapter() {
		if (c4_4xlargeItemProvider == null) {
			c4_4xlargeItemProvider = new C4_4xlargeItemProvider(this);
		}

		return c4_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C4_8xlargeItemProvider c4_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C4_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC4_8xlargeAdapter() {
		if (c4_8xlargeItemProvider == null) {
			c4_8xlargeItemProvider = new C4_8xlargeItemProvider(this);
		}

		return c4_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C3_largeItemProvider c3_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC3_largeAdapter() {
		if (c3_largeItemProvider == null) {
			c3_largeItemProvider = new C3_largeItemProvider(this);
		}

		return c3_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C3_xlargeItemProvider c3_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC3_xlargeAdapter() {
		if (c3_xlargeItemProvider == null) {
			c3_xlargeItemProvider = new C3_xlargeItemProvider(this);
		}

		return c3_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C3_2xlargeItemProvider c3_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC3_2xlargeAdapter() {
		if (c3_2xlargeItemProvider == null) {
			c3_2xlargeItemProvider = new C3_2xlargeItemProvider(this);
		}

		return c3_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C3_4xlargeItemProvider c3_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC3_4xlargeAdapter() {
		if (c3_4xlargeItemProvider == null) {
			c3_4xlargeItemProvider = new C3_4xlargeItemProvider(this);
		}

		return c3_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C3_8xlargeItemProvider c3_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C3_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC3_8xlargeAdapter() {
		if (c3_8xlargeItemProvider == null) {
			c3_8xlargeItemProvider = new C3_8xlargeItemProvider(this);
		}

		return c3_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1e_xlargeItemProvider x1e_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1e_xlargeAdapter() {
		if (x1e_xlargeItemProvider == null) {
			x1e_xlargeItemProvider = new X1e_xlargeItemProvider(this);
		}

		return x1e_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1e_2xlargeItemProvider x1e_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1e_2xlargeAdapter() {
		if (x1e_2xlargeItemProvider == null) {
			x1e_2xlargeItemProvider = new X1e_2xlargeItemProvider(this);
		}

		return x1e_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1e_4xlargeItemProvider x1e_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1e_4xlargeAdapter() {
		if (x1e_4xlargeItemProvider == null) {
			x1e_4xlargeItemProvider = new X1e_4xlargeItemProvider(this);
		}

		return x1e_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1e_8xlargeItemProvider x1e_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1e_8xlargeAdapter() {
		if (x1e_8xlargeItemProvider == null) {
			x1e_8xlargeItemProvider = new X1e_8xlargeItemProvider(this);
		}

		return x1e_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1e_16xlargeItemProvider x1e_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1e_16xlargeAdapter() {
		if (x1e_16xlargeItemProvider == null) {
			x1e_16xlargeItemProvider = new X1e_16xlargeItemProvider(this);
		}

		return x1e_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_32xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1e_32xlargeItemProvider x1e_32xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1e_32xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1e_32xlargeAdapter() {
		if (x1e_32xlargeItemProvider == null) {
			x1e_32xlargeItemProvider = new X1e_32xlargeItemProvider(this);
		}

		return x1e_32xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1_16xlargeItemProvider x1_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1_16xlargeAdapter() {
		if (x1_16xlargeItemProvider == null) {
			x1_16xlargeItemProvider = new X1_16xlargeItemProvider(this);
		}

		return x1_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1_32xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected X1_32xlargeItemProvider x1_32xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.X1_32xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createX1_32xlargeAdapter() {
		if (x1_32xlargeItemProvider == null) {
			x1_32xlargeItemProvider = new X1_32xlargeItemProvider(this);
		}

		return x1_32xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R4_largeItemProvider r4_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR4_largeAdapter() {
		if (r4_largeItemProvider == null) {
			r4_largeItemProvider = new R4_largeItemProvider(this);
		}

		return r4_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R4_xlargeItemProvider r4_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR4_xlargeAdapter() {
		if (r4_xlargeItemProvider == null) {
			r4_xlargeItemProvider = new R4_xlargeItemProvider(this);
		}

		return r4_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R4_2xlargeItemProvider r4_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR4_2xlargeAdapter() {
		if (r4_2xlargeItemProvider == null) {
			r4_2xlargeItemProvider = new R4_2xlargeItemProvider(this);
		}

		return r4_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R4_4xlargeItemProvider r4_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR4_4xlargeAdapter() {
		if (r4_4xlargeItemProvider == null) {
			r4_4xlargeItemProvider = new R4_4xlargeItemProvider(this);
		}

		return r4_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R4_8xlargeItemProvider r4_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR4_8xlargeAdapter() {
		if (r4_8xlargeItemProvider == null) {
			r4_8xlargeItemProvider = new R4_8xlargeItemProvider(this);
		}

		return r4_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R4_16xlargeItemProvider r4_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R4_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR4_16xlargeAdapter() {
		if (r4_16xlargeItemProvider == null) {
			r4_16xlargeItemProvider = new R4_16xlargeItemProvider(this);
		}

		return r4_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R3_largeItemProvider r3_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR3_largeAdapter() {
		if (r3_largeItemProvider == null) {
			r3_largeItemProvider = new R3_largeItemProvider(this);
		}

		return r3_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R3_xlargeItemProvider r3_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR3_xlargeAdapter() {
		if (r3_xlargeItemProvider == null) {
			r3_xlargeItemProvider = new R3_xlargeItemProvider(this);
		}

		return r3_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R3_2xlargeItemProvider r3_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR3_2xlargeAdapter() {
		if (r3_2xlargeItemProvider == null) {
			r3_2xlargeItemProvider = new R3_2xlargeItemProvider(this);
		}

		return r3_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R3_4xlargeItemProvider r3_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR3_4xlargeAdapter() {
		if (r3_4xlargeItemProvider == null) {
			r3_4xlargeItemProvider = new R3_4xlargeItemProvider(this);
		}

		return r3_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected R3_8xlargeItemProvider r3_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.R3_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createR3_8xlargeAdapter() {
		if (r3_8xlargeItemProvider == null) {
			r3_8xlargeItemProvider = new R3_8xlargeItemProvider(this);
		}

		return r3_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P3_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P3_2xlargeItemProvider p3_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P3_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP3_2xlargeAdapter() {
		if (p3_2xlargeItemProvider == null) {
			p3_2xlargeItemProvider = new P3_2xlargeItemProvider(this);
		}

		return p3_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P3_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P3_8xlargeItemProvider p3_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P3_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP3_8xlargeAdapter() {
		if (p3_8xlargeItemProvider == null) {
			p3_8xlargeItemProvider = new P3_8xlargeItemProvider(this);
		}

		return p3_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P3_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P3_16xlargeItemProvider p3_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P3_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP3_16xlargeAdapter() {
		if (p3_16xlargeItemProvider == null) {
			p3_16xlargeItemProvider = new P3_16xlargeItemProvider(this);
		}

		return p3_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P2_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P2_xlargeItemProvider p2_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P2_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP2_xlargeAdapter() {
		if (p2_xlargeItemProvider == null) {
			p2_xlargeItemProvider = new P2_xlargeItemProvider(this);
		}

		return p2_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P2_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P2_8xlargeItemProvider p2_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P2_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP2_8xlargeAdapter() {
		if (p2_8xlargeItemProvider == null) {
			p2_8xlargeItemProvider = new P2_8xlargeItemProvider(this);
		}

		return p2_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P2_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P2_16xlargeItemProvider p2_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.P2_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP2_16xlargeAdapter() {
		if (p2_16xlargeItemProvider == null) {
			p2_16xlargeItemProvider = new P2_16xlargeItemProvider(this);
		}

		return p2_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Generalpurpose} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralpurposeItemProvider generalpurposeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Generalpurpose}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralpurposeAdapter() {
		if (generalpurposeItemProvider == null) {
			generalpurposeItemProvider = new GeneralpurposeItemProvider(this);
		}

		return generalpurposeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Computeoptimized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComputeoptimizedItemProvider computeoptimizedItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Computeoptimized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComputeoptimizedAdapter() {
		if (computeoptimizedItemProvider == null) {
			computeoptimizedItemProvider = new ComputeoptimizedItemProvider(this);
		}

		return computeoptimizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Memoryoptimized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MemoryoptimizedItemProvider memoryoptimizedItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Memoryoptimized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMemoryoptimizedAdapter() {
		if (memoryoptimizedItemProvider == null) {
			memoryoptimizedItemProvider = new MemoryoptimizedItemProvider(this);
		}

		return memoryoptimizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Acceleratedcomputing} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AcceleratedcomputingItemProvider acceleratedcomputingItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Acceleratedcomputing}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAcceleratedcomputingAdapter() {
		if (acceleratedcomputingItemProvider == null) {
			acceleratedcomputingItemProvider = new AcceleratedcomputingItemProvider(this);
		}

		return acceleratedcomputingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Storageoptimized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StorageoptimizedItemProvider storageoptimizedItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Storageoptimized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStorageoptimizedAdapter() {
		if (storageoptimizedItemProvider == null) {
			storageoptimizedItemProvider = new StorageoptimizedItemProvider(this);
		}

		return storageoptimizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G3_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G3_4xlargeItemProvider g3_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G3_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createG3_4xlargeAdapter() {
		if (g3_4xlargeItemProvider == null) {
			g3_4xlargeItemProvider = new G3_4xlargeItemProvider(this);
		}

		return g3_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G3_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G3_8xlargeItemProvider g3_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G3_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createG3_8xlargeAdapter() {
		if (g3_8xlargeItemProvider == null) {
			g3_8xlargeItemProvider = new G3_8xlargeItemProvider(this);
		}

		return g3_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G3_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G3_16xlargeItemProvider g3_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G3_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createG3_16xlargeAdapter() {
		if (g3_16xlargeItemProvider == null) {
			g3_16xlargeItemProvider = new G3_16xlargeItemProvider(this);
		}

		return g3_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.F1_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected F1_2xlargeItemProvider f1_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.F1_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createF1_2xlargeAdapter() {
		if (f1_2xlargeItemProvider == null) {
			f1_2xlargeItemProvider = new F1_2xlargeItemProvider(this);
		}

		return f1_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.F1_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected F1_16xlargeItemProvider f1_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.F1_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createF1_16xlargeAdapter() {
		if (f1_16xlargeItemProvider == null) {
			f1_16xlargeItemProvider = new F1_16xlargeItemProvider(this);
		}

		return f1_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected H1_2xlargeItemProvider h1_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createH1_2xlargeAdapter() {
		if (h1_2xlargeItemProvider == null) {
			h1_2xlargeItemProvider = new H1_2xlargeItemProvider(this);
		}

		return h1_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected H1_4xlargeItemProvider h1_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createH1_4xlargeAdapter() {
		if (h1_4xlargeItemProvider == null) {
			h1_4xlargeItemProvider = new H1_4xlargeItemProvider(this);
		}

		return h1_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected H1_8xlargeItemProvider h1_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createH1_8xlargeAdapter() {
		if (h1_8xlargeItemProvider == null) {
			h1_8xlargeItemProvider = new H1_8xlargeItemProvider(this);
		}

		return h1_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected H1_16xlargeItemProvider h1_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.H1_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createH1_16xlargeAdapter() {
		if (h1_16xlargeItemProvider == null) {
			h1_16xlargeItemProvider = new H1_16xlargeItemProvider(this);
		}

		return h1_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_largeItemProvider i3_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_largeAdapter() {
		if (i3_largeItemProvider == null) {
			i3_largeItemProvider = new I3_largeItemProvider(this);
		}

		return i3_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_xlargeItemProvider i3_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_xlargeAdapter() {
		if (i3_xlargeItemProvider == null) {
			i3_xlargeItemProvider = new I3_xlargeItemProvider(this);
		}

		return i3_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_2xlargeItemProvider i3_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_2xlargeAdapter() {
		if (i3_2xlargeItemProvider == null) {
			i3_2xlargeItemProvider = new I3_2xlargeItemProvider(this);
		}

		return i3_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_4xlargeItemProvider i3_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_4xlargeAdapter() {
		if (i3_4xlargeItemProvider == null) {
			i3_4xlargeItemProvider = new I3_4xlargeItemProvider(this);
		}

		return i3_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_8xlargeItemProvider i3_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_8xlargeAdapter() {
		if (i3_8xlargeItemProvider == null) {
			i3_8xlargeItemProvider = new I3_8xlargeItemProvider(this);
		}

		return i3_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_16xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_16xlargeItemProvider i3_16xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_16xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_16xlargeAdapter() {
		if (i3_16xlargeItemProvider == null) {
			i3_16xlargeItemProvider = new I3_16xlargeItemProvider(this);
		}

		return i3_16xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_metal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I3_metalItemProvider i3_metalItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I3_metal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI3_metalAdapter() {
		if (i3_metalItemProvider == null) {
			i3_metalItemProvider = new I3_metalItemProvider(this);
		}

		return i3_metalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D2_xlargeItemProvider d2_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createD2_xlargeAdapter() {
		if (d2_xlargeItemProvider == null) {
			d2_xlargeItemProvider = new D2_xlargeItemProvider(this);
		}

		return d2_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D2_2xlargeItemProvider d2_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createD2_2xlargeAdapter() {
		if (d2_2xlargeItemProvider == null) {
			d2_2xlargeItemProvider = new D2_2xlargeItemProvider(this);
		}

		return d2_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D2_4xlargeItemProvider d2_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createD2_4xlargeAdapter() {
		if (d2_4xlargeItemProvider == null) {
			d2_4xlargeItemProvider = new D2_4xlargeItemProvider(this);
		}

		return d2_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D2_8xlargeItemProvider d2_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.D2_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createD2_8xlargeAdapter() {
		if (d2_8xlargeItemProvider == null) {
			d2_8xlargeItemProvider = new D2_8xlargeItemProvider(this);
		}

		return d2_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_small} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M1_smallItemProvider m1_smallItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_small}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM1_smallAdapter() {
		if (m1_smallItemProvider == null) {
			m1_smallItemProvider = new M1_smallItemProvider(this);
		}

		return m1_smallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T1_micro} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T1_microItemProvider t1_microItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.T1_micro}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createT1_microAdapter() {
		if (t1_microItemProvider == null) {
			t1_microItemProvider = new T1_microItemProvider(this);
		}

		return t1_microItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_medium} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M1_mediumItemProvider m1_mediumItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_medium}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM1_mediumAdapter() {
		if (m1_mediumItemProvider == null) {
			m1_mediumItemProvider = new M1_mediumItemProvider(this);
		}

		return m1_mediumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_large} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M1_largeItemProvider m1_largeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_large}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM1_largeAdapter() {
		if (m1_largeItemProvider == null) {
			m1_largeItemProvider = new M1_largeItemProvider(this);
		}

		return m1_largeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M1_xlargeItemProvider m1_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M1_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM1_xlargeAdapter() {
		if (m1_xlargeItemProvider == null) {
			m1_xlargeItemProvider = new M1_xlargeItemProvider(this);
		}

		return m1_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C1_medium} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C1_mediumItemProvider c1_mediumItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C1_medium}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC1_mediumAdapter() {
		if (c1_mediumItemProvider == null) {
			c1_mediumItemProvider = new C1_mediumItemProvider(this);
		}

		return c1_mediumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C1_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected C1_xlargeItemProvider c1_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.C1_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createC1_xlargeAdapter() {
		if (c1_xlargeItemProvider == null) {
			c1_xlargeItemProvider = new C1_xlargeItemProvider(this);
		}

		return c1_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Cc2_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Cc2_8xlargeItemProvider cc2_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Cc2_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCc2_8xlargeAdapter() {
		if (cc2_8xlargeItemProvider == null) {
			cc2_8xlargeItemProvider = new Cc2_8xlargeItemProvider(this);
		}

		return cc2_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G2_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G2_2xlargeItemProvider g2_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G2_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createG2_2xlargeAdapter() {
		if (g2_2xlargeItemProvider == null) {
			g2_2xlargeItemProvider = new G2_2xlargeItemProvider(this);
		}

		return g2_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G2_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G2_8xlargeItemProvider g2_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.G2_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createG2_8xlargeAdapter() {
		if (g2_8xlargeItemProvider == null) {
			g2_8xlargeItemProvider = new G2_8xlargeItemProvider(this);
		}

		return g2_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Cg1_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Cg1_4xlargeItemProvider cg1_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Cg1_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCg1_4xlargeAdapter() {
		if (cg1_4xlargeItemProvider == null) {
			cg1_4xlargeItemProvider = new Cg1_4xlargeItemProvider(this);
		}

		return cg1_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M2_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M2_xlargeItemProvider m2_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M2_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM2_xlargeAdapter() {
		if (m2_xlargeItemProvider == null) {
			m2_xlargeItemProvider = new M2_xlargeItemProvider(this);
		}

		return m2_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M2_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M2_2xlargeItemProvider m2_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M2_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM2_2xlargeAdapter() {
		if (m2_2xlargeItemProvider == null) {
			m2_2xlargeItemProvider = new M2_2xlargeItemProvider(this);
		}

		return m2_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M2_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected M2_4xlargeItemProvider m2_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.M2_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createM2_4xlargeAdapter() {
		if (m2_4xlargeItemProvider == null) {
			m2_4xlargeItemProvider = new M2_4xlargeItemProvider(this);
		}

		return m2_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Cr1_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Cr1_8xlargeItemProvider cr1_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Cr1_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCr1_8xlargeAdapter() {
		if (cr1_8xlargeItemProvider == null) {
			cr1_8xlargeItemProvider = new Cr1_8xlargeItemProvider(this);
		}

		return cr1_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I2_xlargeItemProvider i2_xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI2_xlargeAdapter() {
		if (i2_xlargeItemProvider == null) {
			i2_xlargeItemProvider = new I2_xlargeItemProvider(this);
		}

		return i2_xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_2xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I2_2xlargeItemProvider i2_2xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_2xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI2_2xlargeAdapter() {
		if (i2_2xlargeItemProvider == null) {
			i2_2xlargeItemProvider = new I2_2xlargeItemProvider(this);
		}

		return i2_2xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_4xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I2_4xlargeItemProvider i2_4xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_4xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI2_4xlargeAdapter() {
		if (i2_4xlargeItemProvider == null) {
			i2_4xlargeItemProvider = new I2_4xlargeItemProvider(this);
		}

		return i2_4xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected I2_8xlargeItemProvider i2_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.I2_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createI2_8xlargeAdapter() {
		if (i2_8xlargeItemProvider == null) {
			i2_8xlargeItemProvider = new I2_8xlargeItemProvider(this);
		}

		return i2_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Hs1_8xlarge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Hs1_8xlargeItemProvider hs1_8xlargeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Hs1_8xlarge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHs1_8xlargeAdapter() {
		if (hs1_8xlargeItemProvider == null) {
			hs1_8xlargeItemProvider = new Hs1_8xlargeItemProvider(this);
		}

		return hs1_8xlargeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Placementgroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlacementgroupItemProvider placementgroupItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Placementgroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlacementgroupAdapter() {
		if (placementgroupItemProvider == null) {
			placementgroupItemProvider = new PlacementgroupItemProvider(this);
		}

		return placementgroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Rootdevicevolume} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RootdevicevolumeItemProvider rootdevicevolumeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Rootdevicevolume}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRootdevicevolumeAdapter() {
		if (rootdevicevolumeItemProvider == null) {
			rootdevicevolumeItemProvider = new RootdevicevolumeItemProvider(this);
		}

		return rootdevicevolumeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Statustransitionreason} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StatustransitionreasonItemProvider statustransitionreasonItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Statustransitionreason}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStatustransitionreasonAdapter() {
		if (statustransitionreasonItemProvider == null) {
			statustransitionreasonItemProvider = new StatustransitionreasonItemProvider(this);
		}

		return statustransitionreasonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Tags} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagsItemProvider tagsItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Tags}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagsAdapter() {
		if (tagsItemProvider == null) {
			tagsItemProvider = new TagsItemProvider(this);
		}

		return tagsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Instancevpcinfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstancevpcinfoItemProvider instancevpcinfoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.multicloud.aws.ec2.Instancevpcinfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstancevpcinfoAdapter() {
		if (instancevpcinfoItemProvider == null) {
			instancevpcinfoItemProvider = new InstancevpcinfoItemProvider(this);
		}

		return instancevpcinfoItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (instanceec2ItemProvider != null) instanceec2ItemProvider.dispose();
		if (awsaccountItemProvider != null) awsaccountItemProvider.dispose();
		if (awscredentialItemProvider != null) awscredentialItemProvider.dispose();
		if (t2_nanoItemProvider != null) t2_nanoItemProvider.dispose();
		if (t2_microItemProvider != null) t2_microItemProvider.dispose();
		if (t2_smallItemProvider != null) t2_smallItemProvider.dispose();
		if (t2_mediumItemProvider != null) t2_mediumItemProvider.dispose();
		if (t2_largeItemProvider != null) t2_largeItemProvider.dispose();
		if (t2_xlargeItemProvider != null) t2_xlargeItemProvider.dispose();
		if (t2_2xlargeItemProvider != null) t2_2xlargeItemProvider.dispose();
		if (m5_largeItemProvider != null) m5_largeItemProvider.dispose();
		if (m5_xlargeItemProvider != null) m5_xlargeItemProvider.dispose();
		if (m5_2xlargeItemProvider != null) m5_2xlargeItemProvider.dispose();
		if (m5_4xlargeItemProvider != null) m5_4xlargeItemProvider.dispose();
		if (m5_12xlargeItemProvider != null) m5_12xlargeItemProvider.dispose();
		if (m5_24xlargeItemProvider != null) m5_24xlargeItemProvider.dispose();
		if (m4_largeItemProvider != null) m4_largeItemProvider.dispose();
		if (m4_xlargeItemProvider != null) m4_xlargeItemProvider.dispose();
		if (m4_2xlargeItemProvider != null) m4_2xlargeItemProvider.dispose();
		if (m4_10xlargeItemProvider != null) m4_10xlargeItemProvider.dispose();
		if (m4_16xlargeItemProvider != null) m4_16xlargeItemProvider.dispose();
		if (m3_mediumItemProvider != null) m3_mediumItemProvider.dispose();
		if (m3_largeItemProvider != null) m3_largeItemProvider.dispose();
		if (m3_xlargeItemProvider != null) m3_xlargeItemProvider.dispose();
		if (m3_2xlargeItemProvider != null) m3_2xlargeItemProvider.dispose();
		if (c5_largeItemProvider != null) c5_largeItemProvider.dispose();
		if (c5_xlargeItemProvider != null) c5_xlargeItemProvider.dispose();
		if (c5_2xlargeItemProvider != null) c5_2xlargeItemProvider.dispose();
		if (c5_4xlargeItemProvider != null) c5_4xlargeItemProvider.dispose();
		if (c5_9xlargeItemProvider != null) c5_9xlargeItemProvider.dispose();
		if (c5_18xlargeItemProvider != null) c5_18xlargeItemProvider.dispose();
		if (c4_largeItemProvider != null) c4_largeItemProvider.dispose();
		if (c4_xlargeItemProvider != null) c4_xlargeItemProvider.dispose();
		if (c4_2xlargeItemProvider != null) c4_2xlargeItemProvider.dispose();
		if (c4_4xlargeItemProvider != null) c4_4xlargeItemProvider.dispose();
		if (c4_8xlargeItemProvider != null) c4_8xlargeItemProvider.dispose();
		if (c3_largeItemProvider != null) c3_largeItemProvider.dispose();
		if (c3_xlargeItemProvider != null) c3_xlargeItemProvider.dispose();
		if (c3_2xlargeItemProvider != null) c3_2xlargeItemProvider.dispose();
		if (c3_4xlargeItemProvider != null) c3_4xlargeItemProvider.dispose();
		if (c3_8xlargeItemProvider != null) c3_8xlargeItemProvider.dispose();
		if (x1e_xlargeItemProvider != null) x1e_xlargeItemProvider.dispose();
		if (x1e_2xlargeItemProvider != null) x1e_2xlargeItemProvider.dispose();
		if (x1e_4xlargeItemProvider != null) x1e_4xlargeItemProvider.dispose();
		if (x1e_8xlargeItemProvider != null) x1e_8xlargeItemProvider.dispose();
		if (x1e_16xlargeItemProvider != null) x1e_16xlargeItemProvider.dispose();
		if (x1e_32xlargeItemProvider != null) x1e_32xlargeItemProvider.dispose();
		if (x1_16xlargeItemProvider != null) x1_16xlargeItemProvider.dispose();
		if (x1_32xlargeItemProvider != null) x1_32xlargeItemProvider.dispose();
		if (r4_largeItemProvider != null) r4_largeItemProvider.dispose();
		if (r4_xlargeItemProvider != null) r4_xlargeItemProvider.dispose();
		if (r4_2xlargeItemProvider != null) r4_2xlargeItemProvider.dispose();
		if (r4_4xlargeItemProvider != null) r4_4xlargeItemProvider.dispose();
		if (r4_8xlargeItemProvider != null) r4_8xlargeItemProvider.dispose();
		if (r4_16xlargeItemProvider != null) r4_16xlargeItemProvider.dispose();
		if (r3_largeItemProvider != null) r3_largeItemProvider.dispose();
		if (r3_xlargeItemProvider != null) r3_xlargeItemProvider.dispose();
		if (r3_2xlargeItemProvider != null) r3_2xlargeItemProvider.dispose();
		if (r3_4xlargeItemProvider != null) r3_4xlargeItemProvider.dispose();
		if (r3_8xlargeItemProvider != null) r3_8xlargeItemProvider.dispose();
		if (p3_2xlargeItemProvider != null) p3_2xlargeItemProvider.dispose();
		if (p3_8xlargeItemProvider != null) p3_8xlargeItemProvider.dispose();
		if (p3_16xlargeItemProvider != null) p3_16xlargeItemProvider.dispose();
		if (p2_xlargeItemProvider != null) p2_xlargeItemProvider.dispose();
		if (p2_8xlargeItemProvider != null) p2_8xlargeItemProvider.dispose();
		if (p2_16xlargeItemProvider != null) p2_16xlargeItemProvider.dispose();
		if (generalpurposeItemProvider != null) generalpurposeItemProvider.dispose();
		if (computeoptimizedItemProvider != null) computeoptimizedItemProvider.dispose();
		if (memoryoptimizedItemProvider != null) memoryoptimizedItemProvider.dispose();
		if (acceleratedcomputingItemProvider != null) acceleratedcomputingItemProvider.dispose();
		if (storageoptimizedItemProvider != null) storageoptimizedItemProvider.dispose();
		if (g3_4xlargeItemProvider != null) g3_4xlargeItemProvider.dispose();
		if (g3_8xlargeItemProvider != null) g3_8xlargeItemProvider.dispose();
		if (g3_16xlargeItemProvider != null) g3_16xlargeItemProvider.dispose();
		if (f1_2xlargeItemProvider != null) f1_2xlargeItemProvider.dispose();
		if (f1_16xlargeItemProvider != null) f1_16xlargeItemProvider.dispose();
		if (h1_2xlargeItemProvider != null) h1_2xlargeItemProvider.dispose();
		if (h1_4xlargeItemProvider != null) h1_4xlargeItemProvider.dispose();
		if (h1_8xlargeItemProvider != null) h1_8xlargeItemProvider.dispose();
		if (h1_16xlargeItemProvider != null) h1_16xlargeItemProvider.dispose();
		if (i3_largeItemProvider != null) i3_largeItemProvider.dispose();
		if (i3_xlargeItemProvider != null) i3_xlargeItemProvider.dispose();
		if (i3_2xlargeItemProvider != null) i3_2xlargeItemProvider.dispose();
		if (i3_4xlargeItemProvider != null) i3_4xlargeItemProvider.dispose();
		if (i3_8xlargeItemProvider != null) i3_8xlargeItemProvider.dispose();
		if (i3_16xlargeItemProvider != null) i3_16xlargeItemProvider.dispose();
		if (i3_metalItemProvider != null) i3_metalItemProvider.dispose();
		if (d2_xlargeItemProvider != null) d2_xlargeItemProvider.dispose();
		if (d2_2xlargeItemProvider != null) d2_2xlargeItemProvider.dispose();
		if (d2_4xlargeItemProvider != null) d2_4xlargeItemProvider.dispose();
		if (d2_8xlargeItemProvider != null) d2_8xlargeItemProvider.dispose();
		if (m1_smallItemProvider != null) m1_smallItemProvider.dispose();
		if (t1_microItemProvider != null) t1_microItemProvider.dispose();
		if (m1_mediumItemProvider != null) m1_mediumItemProvider.dispose();
		if (m1_largeItemProvider != null) m1_largeItemProvider.dispose();
		if (m1_xlargeItemProvider != null) m1_xlargeItemProvider.dispose();
		if (c1_mediumItemProvider != null) c1_mediumItemProvider.dispose();
		if (c1_xlargeItemProvider != null) c1_xlargeItemProvider.dispose();
		if (cc2_8xlargeItemProvider != null) cc2_8xlargeItemProvider.dispose();
		if (g2_2xlargeItemProvider != null) g2_2xlargeItemProvider.dispose();
		if (g2_8xlargeItemProvider != null) g2_8xlargeItemProvider.dispose();
		if (cg1_4xlargeItemProvider != null) cg1_4xlargeItemProvider.dispose();
		if (m2_xlargeItemProvider != null) m2_xlargeItemProvider.dispose();
		if (m2_2xlargeItemProvider != null) m2_2xlargeItemProvider.dispose();
		if (m2_4xlargeItemProvider != null) m2_4xlargeItemProvider.dispose();
		if (cr1_8xlargeItemProvider != null) cr1_8xlargeItemProvider.dispose();
		if (i2_xlargeItemProvider != null) i2_xlargeItemProvider.dispose();
		if (i2_2xlargeItemProvider != null) i2_2xlargeItemProvider.dispose();
		if (i2_4xlargeItemProvider != null) i2_4xlargeItemProvider.dispose();
		if (i2_8xlargeItemProvider != null) i2_8xlargeItemProvider.dispose();
		if (hs1_8xlargeItemProvider != null) hs1_8xlargeItemProvider.dispose();
		if (placementgroupItemProvider != null) placementgroupItemProvider.dispose();
		if (rootdevicevolumeItemProvider != null) rootdevicevolumeItemProvider.dispose();
		if (statustransitionreasonItemProvider != null) statustransitionreasonItemProvider.dispose();
		if (tagsItemProvider != null) tagsItemProvider.dispose();
		if (instancevpcinfoItemProvider != null) instancevpcinfoItemProvider.dispose();
	}

}
