<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="all" nsURI="http://occiware.org/occi/multicloud/ecore" nsPrefix="all">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="occi" value="http://schemas.ogf.org/occi/core/ecore"/>
    <details key="infrastructure" value="http://schemas.ogf.org/occi/infrastructure/ecore"/>
    <details key="monitoring" value="http://schemas.ogf.org/occi/monitoring/ecore"/>
    <details key="accounts" value="http://occiware.org/occi/infrastructure/security/ecore"/>
    <details key="regions" value="http://occiware.org/occi/infrastructure/locations/ecore"/>
    <details key="awsaccounts" value="http://occiware.org/occi/aws/security/ecore"/>
    <details key="awsregions" value="http://occiware.org/occi/infrastructure/locations/aws/ecore"/>
    <details key="ec2" value="http://occiware.org/occi/infrastructure/aws/ecore"/>
    <details key="vmware" value="http://occiware.org/occi/infrastructure/vmware/ecore"/>
    <details key="interoperability" value="http://occiware.org/occi/multicloud/specialfeatures/ecore"/>
    <details key="oscore" value="http://occiware.org/occi/infrastructure/openstack/ecore"/>
    <details key="identity" value="http://occiware.org/occi/infrastructure/openstack/security/ecore"/>
  </eAnnotations>
</ecore:EPackage>
